spring:
  application:
    name: BankApp_Thymeleaf

  datasource:
    url: jdbc:mysql://localhost:3306/BankAppDB
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8083